server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  datasource:
    url : jdbc:mysql://localhost:3306/account?useSSL=false&createDatabaseIfNotExist=true
    username : root
    password : root
    testWhileIdle : true
    validationQuery : SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
    database: default
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true
    
jsondoc:
  version: 1.0
  basePath: http://localhost:2222
  packages[0]: pl.piomin.microservices.account.controller
  packages[1]: pl.piomin.microservices.account.model
  playgroundEnabled: true
  jsondoc.displayMethodAs: URI
  
    